apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coturn.fullname" . }}-config
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
data:
  turnserver.conf: |
    listening-port={{ .Values.ports.listening }}
    min-port={{ .Values.ports.minRelay }}
    max-port={{ .Values.ports.maxRelay }}
    realm={{ .Values.credentials.realm }}
    user={{ .Values.credentials.username }}:{{ .Values.credentials.password }}
    lt-cred-mech
    no-tls
    no-dtls
    external-ip=__NODE_EXTERNAL_IP__
