# gz-viewer: nginx serving viewer.html with runtime endpoint injection

FROM registry.access.redhat.com/ubi10/ubi-minimal:latest

RUN microdnf install -y nginx sed && microdnf clean all

COPY nginx.conf /etc/nginx/nginx.conf
COPY viewer.html /opt/viewer/viewer.html.template

RUN mkdir -p /opt/viewer/html && \
    chmod -R 777 /opt/viewer/html /var/log/nginx /var/lib/nginx /run

RUN printf '#!/bin/sh\n\
sed -e "s|__WS_URL__|${WS_URL}|g" \\\n\
    -e "s|__MEDIAMTX_BASE__|${MEDIAMTX_BASE}|g" \\\n\
    -e "s|__MEDIAMTX_API__|${MEDIAMTX_API}|g" \\\n\
    < /opt/viewer/viewer.html.template \\\n\
    > /opt/viewer/html/index.html\n\
exec nginx -g '"'"'daemon off;'"'"'\n' > /docker-entrypoint.sh \
  && chmod +x /docker-entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["/docker-entrypoint.sh"]
