apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mediamtx.fullname" . }}-config
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
data:
  mediamtx.yml: |
    logLevel: info

    authMethod: internal
    authInternalUsers:
      - user: any
        ips: []
        permissions:
          - action: read
          - action: publish
          - action: api
          - action: metrics
          - action: pprof
          - action: playback

    api: yes
    apiAddress: :9997

    rtsp: yes
    rtspAddress: :8554

    webrtc: yes
    webrtcAddress: :8889

    webrtcLocalUDPAddress: ""
    webrtcIPsFromInterfaces: yes
    webrtcAdditionalHosts: []

    {{- if or .Values.coturn.discovery .Values.coturn.host }}
    webrtcICEServers2:
      - url: turn:{{ if .Values.coturn.discovery }}__COTURN_HOST__{{ else }}{{ .Values.coturn.host }}{{ end }}:{{ .Values.coturn.port }}
        username: {{ .Values.coturn.username }}
        password: {{ .Values.coturn.password }}
    {{- end }}

    hls: yes
    hlsAddress: :8888

    pathDefaults:

    paths:
      ~^(.+)$:
