apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediamtx.fullname" . }}
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mediamtx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mediamtx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mediamtx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["/mediamtx.yml"]
        ports:
        - containerPort: 8889
          name: webrtc
        - containerPort: 9997
          name: api
        - containerPort: 8554
          name: rtsp
        - containerPort: 8888
          name: hls
        volumeMounts:
        - name: config
          mountPath: /mediamtx.yml
          subPath: mediamtx.yml
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "mediamtx.fullname" . }}-config
