{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "viewer.fullname" . }}
  labels:
    {{- include "viewer.labels" . | nindent 4 }}
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ include "viewer.fullname" . }}
  port:
    targetPort: http
{{- end }}
