{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gz-{{ .Values.engineer }}
  labels:
    {{- include "gzsim.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ include "gzsim.fullname" . }}-ws
  port:
    targetPort: ws
{{- end }}
