image:
  repository: bluenviron/mediamtx
  tag: latest
  pullPolicy: IfNotPresent

initImage:
  repository: registry.access.redhat.com/ubi10/ubi-minimal
  tag: latest

coturn:
  discovery: true
  host: ""
  port: 3478
  username: gzsim
  password: gzsimpass

route:
  enabled: true

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
